name: ctec
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - cuda-version=12.9      # keep this so conda chooses matching CUDA toolkit
  - cudnn=8.9.7.29         # keep if you want cudnn from conda rather than pip
  - pip:
      - absl-py==2.2.2
      - annotated-types==0.7.0
      - attrs==25.3.0
      - blinker==1.9.0
      - brax==0.12.1
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - chex==0.1.86
      - click==8.2.1
      - cloudpickle==3.1.1
      - colorlog==6.9.0
      - contourpy==1.3.2
      - csv-logger==1.3.0
      - cycler==0.12.1
      - debugpy==1.8.14
      - distrax==0.1.5
      - dm-env==1.6
      - dm-haiku==0.0.11
      - dm-tree==0.1.9
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - etils==1.12.2
      - exceptiongroup==1.3.0
      - farama-notifications==0.0.4
      - flask==3.1.1
      - flask-cors==6.0.0
      - flax==0.8.4
      - fonttools==4.58.0
      - fsspec==2025.5.0
      - gast==0.6.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - glfw==2.9.0
      - grpcio==1.71.0
      - gym==0.26.2
      - gym-notices==0.0.8
      - gymnasium==1.1.1
      - gymnax==0.0.8
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - ipykernel==6.14.0
      - ipython==8.4.0
      - itsdangerous==2.2.0
      - jax==0.4.25
      - jaxopt==0.8.5
      - jinja2==3.1.6
      - jmp==0.0.4
      - joblib==1.5.0
      - jupyter-core==5.7.2
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.8.0
      - mdurl==0.1.2
      - ml-collections==1.1.0
      - ml-dtypes==0.5.1
      - msgpack==1.1.0
      - mujoco==3.2.7
      - mujoco-mjx==3.2.7
      - mypy-extensions==1.1.0
      - networkx==3.4.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.9.0.13
      - nvidia-cuda-cupti-cu12==12.4.99
      - nvidia-cufft-cu12==11.2.0.44
      - nvidia-cusolver-cu12==11.7.4.40
      - nvidia-cusparse-cu12==12.5.9.5
      - nvidia-nvjitlink-cu12==12.9.41
      - opencv-python==4.11.0.86
      - opt-einsum==3.4.0
      - optax==0.2.2
      - orbax-checkpoint==0.5.18
      - pandas==2.2.3
      - patsy==1.0.1
      - pillow==11.2.1
      - pluggy==1.6.0
      - protobuf==6.31.0
      - psutil==7.0.0
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pygame==2.6.1
      - pyinstrument==4.6.0
      - pyopengl==3.1.9
      - pyparsing==3.2.3
      - pyrallis==0.3.1
      - pytest==7.4.4
      - pytinyrenderer==0.0.14
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==26.4.0
      - requests==2.32.3
      - rich==14.0.0
      - scikit-image==0.22.0
      - scikit-learn==1.6.1
      - scipy==1.12.0
      - seaborn==0.13.2
      - sentry-sdk==2.29.1
      - setproctitle==1.3.6
      - shtab==1.7.2
      - six==1.16.0
      - smmap==5.0.2
      - statsmodels==0.14.1
      - tabulate==0.9.0
      - tensorboardx==2.6.2.2
      - tensorflow-probability==0.25.0
      - tensorstore==0.1.75
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - tomli==2.2.1
      - toolz==1.0.0
      - tornado==6.5
      - trimesh==4.6.10
      - typeguard==4.4.2
      - typing-extensions==4.13.2
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1
      - tyro==0.9.16
      - tzdata==2025.2
      - urllib3==2.4.0
      - wandb==0.19.11
      - wandb-osh==1.2.2
      - werkzeug==3.1.3
      - wonderwords==2.2.0
      - wrapt==1.17.2
